language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t gbelinelo/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true gbelinelo/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "sa-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-sa-east-1-934285670803"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $access_key_id
    secret_access_key:
        secure: "$secret_access_key"